name: Export OpenTelemetry Traces to Dash0
on:
  workflow_run:
    workflows:
      - "Deploy MkDocs to GitHub Pages"
    types:
      - completed
jobs:
  export-trace:
    runs-on: ubuntu-latest
    steps:
      - name: Export Workflow Trace
        uses: corentinmusard/otel-cicd-action@v1
        with:
          otlpEndpoint: ${{ secrets.DASH0_OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.DASH0_OTLP_HEADERS }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          runId: ${{ github.event.workflow_run.id }}
